// This file was generated by Prisma, and assumes Prisma commands run through Bun.

import { defineConfig } from "prisma/config";
import { buildDatabaseUrl } from "./app/config/database";

/** Prisma CLI configuration. */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(process.env),
    shadowDatabaseUrl: buildDatabaseUrl(
      process.env,
      process.env.DATABASE_SHADOW_NAME,
    ),
  },
});
